# Generated by Django 6.1.1 on 2026-09-24 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG'), ('TPU', 'TPU (Flexível)'), ('RESINA', 'Resina UV')], max_length=20)),
                ('cor', models.CharField(max_length=50)),
                ('preco_por_grama', models.DecimalField(decimal_places=4, max_digits=6)),
                ('em_estoque', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('peso_gramas', models.IntegerField()),
                ('tempo_impressao_minutos', models.IntegerField()),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('filamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='core.filamento')),
            ],
        ),
    ]
